### ISSUE TITLE
Error sending logs

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#634] opened 2015-12-24 10:52 UTC
A user sent us the logs of its server, but the file is empty. Looks like one of the logs file has been updated while we were reading it. Here's a message found in home error log:
```
{ [Error: Didn't get expected byte count
expect: 156233808
actual: 156328639]
  code: undefined,
  path: '/usr/local/var/log/cozy/data-system.log',
  fstream_type: 'File',
  fstream_path: '/usr/local/var/log/cozy/data-system.log',
  fstream_class: 'FileReader',
  fstream_stack: 
   [ 'ReadStream.<anonymous> (/usr/local/cozy/apps/home/node_modules/fstream/lib/file-reader.js:65:12)',
     'ReadStream.emit (events.js:117:20)',
     '_stream_readable.js:944:16',
     'process._tickCallback (node.js:448:13)' ] }
Error: Didn't get expected byte count
expect: 156233808
actual: 156328639
    at decorate (/usr/local/cozy/apps/home/node_modules/fstream/lib/abstract.js:67:36)
    at FileReader.Abstract.error (/usr/local/cozy/apps/home/node_modules/fstream/lib/abstract.js:61:12)
    at ReadStream.<anonymous> (/usr/local/cozy/apps/home/node_modules/fstream/lib/file-reader.js:65:12)
    at ReadStream.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
```

**Comment by poupotte** [comment] 2016-01-18 08:27
I close this issue because it's a duplicate of #579 .

**Closed by poupotte** 2016-01-18 08:27 UTC
Labels: bug, duplicate
