### ISSUE TITLE
[new home] Intermittent error showing up in the console

### ISSUE THREAD

**Issue by bnjbvr** [cozy/cozy-home#356] opened 2015-05-19 08:35 UTC
Sorry guys, for this one I don't have any steps to reproduce, it just happens after one or two minutes on my instance...

```
Error: Server error occured
Stack trace:
exports.request/<.error@https://guesswho.cozycloud.cc/javascripts/app.js:553:25
jQuery.Callbacks/fire@https://guesswho.cozycloud.cc/javascripts/vendor.js:1171:10
jQuery.Callbacks/self.fireWith@https://guesswho.cozycloud.cc/javascripts/vendor.js:1289:7
done@https://guesswho.cozycloud.cc/javascripts/vendor.js:7526:1
.send/callback@https://guesswho.cozycloud.cc/javascripts/vendor.js:8305:8
 app.js:965:9
TypeError: res is undefined app.js:967:6
```

**Comment by frankrousseau** [comment] 2015-05-19 08:44
Thank you for reporting.

**Comment by bnjbvr** [comment] 2015-05-19 09:02
I don't experience this issue on a cozy instance which already has photos, so I guess this is related to the preloading of thumbnails...

**Comment by frankrousseau** [comment] 2015-06-07 21:03
Ok thank you. It should be related to that, because, I can't reproduce the problem.

**Comment by clochix** [comment] 2015-06-15 13:09
@bnjbvr I'll close this for now, don't hesitate to re-open the ticket if you encounter again the error.

**Closed by clochix** 2015-06-15 13:09 UTC
Labels: 4 - QA, bug
