### ISSUE TITLE
back home doesn't work in some cases

### ISSUE THREAD

**Issue by Benibur** [cozy/cozy-home#531] opened 2015-10-07 10:04 UTC
I opened the mail application : "we need to index you mails, this screen will update soon" or something like that.
There was a spinner but I decided to go bak to home with the top left buton "back home" , and it worked.

But few seconds after, without I did anthing, the mail app went back on the foreground. 

1/ that was a bit invasive, it is not because the mail app has finished its work that it can come foreground by itself.

2/ the url did not reflect that I was back on the mail app, so when clicking on the "back home" button again, it did not work since the url was still "mydomain.cozycloud.cc/#home" whereas I was in the mail app.

**Comment by aenario** [comment] 2015-10-27 16:42
This is a duplicate of https://github.com/cozy/cozy-home/issues/551

Thanks for reporting :-)

**Closed by aenario** 2015-10-27 16:42 UTC
Labels: bug
