### ISSUE TITLE
Hide installed apps from marketplace

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#330] opened 2015-03-27 11:09 UTC
Some users are disturbed by the fact that installed apps are still shown in Marketplace. Hiding them would be nice.

**Comment by frankrousseau** [comment] 2015-03-27 13:26
That's not the intended behavior. It's a bug.

**Comment by frankrousseau** [comment] 2015-06-01 11:37
It will be fixed with the new version. Thank you for reporting.

**Closed by frankrousseau** 2015-06-01 11:37 UTC
Labels: bug
