### ISSUE TITLE
"install your app" input 

### ISSUE THREAD

**Issue by Benibur** [cozy/cozy-home#307] opened 2015-02-25 17:32 UTC
When you are in the market place, wherever the focus is, when you press any key, you leave the market place to go on the home.
This is especially a problem when you need to paste an URL in the "install your app" input text.
ps : this bug has been seen and can be repeated in "ben-test" vm, but it's ok on 2 other vm... strange.

**Comment by poupotte** [comment] 2015-02-26 16:43
mmm... strange, I don't arrive to reproduce your issue on your vm "ben-test" (firefox and chrome).

**Comment by poupotte** [comment] 2015-02-27 12:18
@Benibur can't reproduce this issue. @frankrousseau , I propose to close this issue. If someone else has this bug, we'll reopen it.

**Closed** 2015-02-27 12:19 UTC
Labels: bug
