### ISSUE TITLE
(minor) Persistent update notifications even though updates are done

### ISSUE THREAD

**Issue by goofy-bz** [cozy/cozy-home#308] opened 2015-02-25 20:44 UTC
I have currently 6 notifications for updates
photos/contacts/emails/files/calendar and platform
though I already updated everything (with no apparent problem, things are improving !)

The user should not be obliged to click on "ignore them all" to remove the notifications that are no longer necessary.

**Comment by frankrousseau** [comment] 2015-02-25 22:57
You're right, these notifications are meaningless once apps are updated.

**Comment by jsilvestre** [comment] 2015-02-26 07:08
This is a duplicate of https://github.com/cozy/cozy-home/issues/259

**Comment by jsilvestre** [comment] 2015-02-26 07:08
This is a duplicate of https://github.com/cozy/cozy-home/issues/259

**Comment by clochix** [comment] 2015-10-13 15:08
I think this has been fixed for a while. @goofy-bz could we close this one ?

**Comment by goofy-bz** [comment] 2015-10-13 16:57
i think yes :) Will report if any zombie prob of the kind

**Comment by clochix** [comment] 2015-10-14 08:37
Thanks prof !

**Closed by clochix** 2015-10-14 08:37 UTC
Labels: 0 - Backlog, bug, duplicate
