### ISSUE TITLE
Can't start installed apps, icon spinning then change to broken

### ISSUE THREAD

**Issue by dkm** [cozy/cozy-home#400] opened 2015-06-17 11:49 UTC
After reading about the new release, I logged in my cozy. I started the photo app without prob, then went back to home: first surprise=> icon for photo is the spinning one. Then I click on file => spinning also and nothing else happens. Finally the nirc one, spinning also, still nothing else.... Then nirc started correctly after a few seconds. Went back to home => the 3 icons still spinning.
File icon changed to the "broken one" and popup showed "This app cannot start. Error was : Installation timeout :
Installation timeout"
In the background, I can see that File icon is back to its correct state.
Photo and nirc still spinning, but both app can be opened correctly now. Only the File app seems to have problem as now, I have "{"error":"{ error: 'Application is not authenticated' }"}" when trying to open it.

**Comment by clochix** [comment] 2015-06-17 15:53
Thanks for reporting @dkm. Could you provide some context : are you self-hosted or on an instance we host ?
What's the version of the applications of the platform (Home…)

@poupotte : the error message looks like the issue you just fixed some hours ago, do you think it may be the same ?

**Comment by dkm** [comment] 2015-06-17 20:54
On 17-06-2015 17:53, Clochix wrote:
> Thanks for reporting @dkm [1]. Could you provide some context : are
> you self-hosted or on an instance we host ?

instance you host

>  What's the version of the applications of the platform (Home…)


files -  1.1.8 - started
nirc -  1.0.0 - started
photos -  1.0.13 - stopped

Data System: 2.0.0
Proxy: 2.0.0
Home: 2.0.1
Controller: 2.0.24

Note that when starting photo app, its icon changes to the spinning one 
and stays that way (app works correctly)

**Comment by poupotte** [comment] 2015-06-18 14:30
Hello @dkm,

We have corrected some problems in data-system yesterday and this morning. It should fixed your issues.
You can try to update your stack or wait, we'll update all cozy this afternoon.

Don't hesitate to tell us if your cozy continue to have problems after update.

**Comment by dkm** [comment] 2015-06-18 15:12
Hi!
Thanks for the support.
I've updated everything using the update all button and everything went fine.

But still, file app still displays the auth problem (I tried to stop it first). nirc and photo app work fine, but photo icon in home page is still spinning :) After stopping it (through the status page), it seems to be working fine.

I hope you can make some sense from this report... I'm doing the best I can to give exact step :)

**Comment by poupotte** [comment] 2015-06-18 15:30
Thanks @dkm ,

For file application : auth problem disappears afterthe application restart ? If problem persists, you can try to reinstall it.
For photo application : it's an known issue (#407), I'm working on it.

**Comment by clochix** [comment] 2015-06-22 12:07
@dkm can w consider the initial problem is solved and close this ticket ?
For photo application, resolution will be in #407.
For file application, do you still have the problem ?

**Comment by dkm** [comment] 2015-06-22 12:43
I can say that I have not seen the erratic behavior again. I let you decide if it is fixed or not.
As for the link with #407 , again, I let you decide if it's relevant or not. In my case, it was not a duplicated icon but an incorrect one.

**Comment by clochix** [comment] 2015-06-22 12:47
Thanks @dkm, I will mark this as resolved for now, as I'm unable to reproduce. If you face this problem again, don't hesitate to come back here ;-)

**Closed** 2015-07-02 07:42 UTC
Labels: 5 - published, bug
