### ISSUE TITLE
Scrolling on ipad's integrated safari doesn't work

### ISSUE THREAD

**Issue by bnjbvr** [cozy/cozy-home#251] opened 2014-12-21 21:09 UTC
Using latest iOS and integrated Safari on an iPad, if you try to scroll in the app's iframe, nothing happens. Maybe adding something like `scrolling="auto"` to the iframe tag should do the trick?

**Comment by m4dz** [comment] 2015-02-09 17:18
My firsts tests confirms that we have a problem with long iframes. It relies on:
- how Safari mobile handles the scrolling event and the viewport (Apple made a specific style for this: http://stackoverflow.com/questions/4599153/iframes-and-the-safari-on-the-ipad-how-can-the-user-scroll-the-content)
- fake scrollers that can simulate a real scroll as Safari mobile expect it (and as we use nice scroll, it may introduces collateral bugs).

I'll try to fix the iframe problem first before considering nicescroll responsibility (as I think it probably does not take part of iframe scrolling, but may have problem on long home views)

**Comment by frankrousseau** [comment] 2015-03-01 13:51
We removed the top bar on iPad. So the scrolling should be back. Could you try again @bnjbvr ?

**Comment by bnjbvr** [comment] 2015-03-01 15:14
Just updated the entire platform via the Update button in my cozy's interface and the top bar is still there. Is there anything else I should do?

**Comment by frankrousseau** [comment] 2015-03-01 17:42
Weird. I will get an ipad and will try directly on it. In fact we removed the top bar for resolution less wide than 900px.

**Comment by frankrousseau** [comment] 2015-03-01 17:43
Whatever thank you for trying again.

**Comment by m4dz** [comment] 2015-03-02 10:32
@frankrousseau I also still have the topbar on iPad and on desktop browser below width < 900px. Was the fix merged and published?

Also @bnjbvr, I tried with long-height apps such as emails and the scrolling works well (even with the topbar), and unlike my first thoughts and tests, the scroll works very well. Is the problem occurs on Kresus specifically?

**Comment by bnjbvr** [comment] 2015-03-02 10:37
As stated on IRC, feeds, bookmarks and tasky have the same issue.

**Comment by m4dz** [comment] 2015-03-02 10:38
Ok, nevermind: the scroll works well in messages list in emails becuase of the messages-list panel that have a `overflow-y: auto`. So the scrolling works for overflowed divs. I'll check for iframes directly…

**Comment by m4dz** [comment] 2015-03-02 11:10
So, after more tests:
- the content can be scrolled if enclosed in an overflowed div
- the iframe embedded in home cannot be scrolled
- add `-webkit-overflow-scrolling:touch` doesn't change anything (due to nicescroll? maybe but I'm not sure…)

If we remove the height on the iframes' parent div, then scrolling works well, but apps using a `body { height: 100% }` such as emails are messed (because their _window_ container – the iframe – doesn't ave any explicit height).

We've got the causes, let's try to find a fix now :wink:!

**Comment by clochix** [comment] 2015-06-16 11:45
@m4dz is this ticket still relevant with the new Home ?

**Comment by clochix** [comment] 2015-07-30 10:23
ping @bnjbvr and @m4dz

**Comment by m4dz** [comment] 2015-07-30 10:28
Sadly, it's still relevant, but not related to home in fact: scrolling in a iframe isn't trivial if the app implement anything other than an `overflow-y: scroll` rule. So, this issue is finally not related to Home (which only display its iframe) but to the incirmined apps that tries to overrides the native scroll.

**Comment by bnjbvr** [comment] 2015-07-30 10:29
Roger that last @m4dz comment: scrolling on tasky works, not on kresus. I'll open an issue on Kresus and will discuss it there.

**Comment by frankrousseau** [comment] 2015-08-01 13:10
Thank you all for your participation. I think we can close this one. If someone thinks I'm wrong, feel free to reopen it.

**Closed by frankrousseau** 2015-08-01 13:10 UTC
Labels: 0 - Backlog, bug
